eithon:
  UseMarkUpForMessages: 1
  UseWrappingForMessages: 1
  
  #
  # Debug level
  #  0 = NONE (no debug messages)
  #  1 = MAJOR (only major messages)
  #  2 = MINOR (also minor messages)
  #  3 = VERBOSE (all messages)
  #
  DebugLevel: 1
  
#
# The time span that a player may be inactive before we stop the play time timer.
AllowedInactivityTimeSpan: 5m

#
# The time span between saving the current statistics.
# This is the time that you risk to lose statistics for if your server crashes.
TimeSpanBetweenSave: 5m

#
# The time of day to archive the day statistics. Recommended: 00:00
ArchiveAtTimeOfDay: 00:00

#
# The time span that a player needs to be active during a day to get another "consecutive day".
TimeSpanPerDayForConsecutiveDays: 1h

database:
  Name: eithon_stats
  Hostname: localhost
  Port: 3306
  Username: eithon_plugin
  Password: 94SnHAGP3RV0mESN

# TST
#  Name: TST_e_stats
#  Hostname: rookgard.eithon.net
#  Port: 3307
#  Username: TST_e_plugin
#  Password: bWfRHZsAy42RdFBJ

# DEV
#  Name: DEV_e_stats
#  Hostname: rookgard.eithon.net
#  Port: 3307
#  Username: DEV_e_plugin
#  Password: J5FE9EFCD1GX8tjg

messages:
  
  #
  # Parameters: -
  PlayerIdle: Idle

  #
  # Parameters: <player name> (%s)
  PlayerStarted: Started recording play time for player %s.

  #
  # Parameters: <player name> (%s)
  PlayerStopped: Stopped recording play time for player %s.

  #
  # Parameters: <play time> (%s) <player name> (%s) <total play time> (%s) 
  PlayTimeAdded: Added %s play time to player %s, resulting in a total play time of %s.

  #
  # Parameters: <play time> (%s) <player name> (%s) <total play time> (%s) 
  ConsecutiveDaysAdded: Added %d consecutive days to player %s, resulting in a total of %d consecutive days.

  #
  # Parameters: <play time> (%s) <player name> (%s) <total play time> (%s) 
  PlacedBlocksAdded: Added %d placed blocks to player %s, resulting in a total of %d placed blocks.

  #
  # Parameters: <play time> (%s) <player name> (%s) <total play time> (%s) 
  BrokenBlocksAdded: Added %d broken blocks to player %s, resulting in a total of %d broken blocks.

  #
  # Parameters: <play time> (%s) <player name> (%s) <total play time> (%s) 
  PlayTimeRemoved: Removed %s play time from player %s, resulting in a total play time of %s.

  #
  # Parameters: <play time> (%s) <player name> (%s) <total play time> (%s) 
  ConsecutiveDaysRemoved: Removed %d consecutive days from player %s, resulting in a total of %d consecutive days.

  #
  # Parameters: <play time> (%s) <player name> (%s) <total play time> (%s) 
  PlacedBlocksRemoved: Removed %d placed blocks from player %s, resulting in a total of %d placed blocks.

  #
  # Parameters: <play time> (%s) <player name> (%s) <total play time> (%s) 
  BrokenBlocksRemoved: Removed %d broken blocks from player %s, resulting in a total of %d broken blocks.

  #
  # Parameters: <player name> (%s)
  PlayTimeReset: Took away all play time from player %s.

  #
  # Parameters: -
  Saved: Saved play times for all logged in players.

  #
  # AFK message when detected by the plugin
  # Parameters: -
  InactivityDetected: Inactivity detected

  #
  # AFK default description (when issuing the command /stats afk, but without a description).
  # Parameters: -
  DefaultAfkDescription: BRB
  
  #
  #
  # Parameters: <Player> (%s), <Description> (%s)
  ToAfkBroadcast: " [i]- [color=darkaqua]%s[/color] is AFK: %s"
  
  #
  #
  # Parameters: <Player> (%s)
  FromAfkBroadcast: " [i]- [color=darkaqua]%s[/color] is back"
  
  #
  #
  # Parameters: -
  StatusOnline: "Online"
  
  #
  #
  # Parameters: -
  StatusOffline: "Offline"
  
  #
  # 
  # Parameters: <Description> (%s)
  StatusAfk: "AFK (%s)"
  
  #
  # The following messages have the following possible parameters
  # %PLAYER_NAME%: The name of the player that the statistics is for.
  # %STATUS_DESCRIPTION%: Status (online/offline/afk (reason)), see StatusOnline, StatusOffline, StatusAfk
  # %BLOCKS_BROKEN%: The total number of blocks that the player has broken.
  # %BLOCKS_CREATED%: The total number of blocks that the player has created.
  # %BLOCKS_CREATED_OR_BROKEN%: The total number of blocks that the player has created or broken (the sum).
  # %CHAT_ACTIVITIES%: The number of chats that the player has sent
  # %INTERVALS%: The number of time intervals that has been recorded for the player.  
  # %TOTAL_PLAY_TIME%: The total play time for the player.
  # %LONGEST_INTERVAL%: The longest time that the player has played without a break.
  # %LATEST_INTERVAL%: The latest recorded play time for the player.
  # %CONSECUTIVE_DAYS%: The number of consecutive days that the player has.
  # %LAST_CONSECUTIVE_DAY%: The last date that the player received a consecutive day.
  TimeStats: "%PLAYER_NAME%: %TOTAL_PLAY_TIME% in %INTERVALS% intervals (longest %LONGEST_INTERVAL%, latest %LATEST_INTERVAL%) Status: %STATUS_DESCRIPTION%"
  ChatStats: "%PLAYER_NAME%: %CHAT_ACTIVITIES% chats"
  BlockStats: "%PLAYER_NAME%: %BLOCKS_CREATED% blocks created (broken %BLOCKS_BROKEN%)"
  PlayerStats: "	[hl=1][ [color=aqua]%PLAYER_NAME% stats[/color] ]\n[color=darkgrey]  -[/color] [color=darkaqua]Playtime:[/color] %TOTAL_PLAY_TIME% ([color=aqua]%CONSECUTIVE_DAYS%[/color] Consecutive Days!)\n[color=darkgrey]  -[/color] [color=darkaqua]Messages Sent:[/color] %CHAT_ACTIVITIES% \n[color=darkgrey]  -[/color] [color=darkaqua]Blocks Placed/Broken:[/color] %BLOCKS_CREATED%/%BLOCKS_BROKEN% \n[color=darkgrey]  -[/color] [color=darkaqua]Status:[/color] %STATUS_DESCRIPTION% "
  DiffStats: "%PLAYER_NAME%: %TOTAL_PLAY_TIME%, %CHAT_ACTIVITIES% chats, %BLOCKS_CREATED_OR_BROKEN% blocks created or broken)"

