#
# Debug level
#	0 = NONE (no debug messages)
#	1 = MAJOR (only major messages)
#	2 = MINOR (also minor messages)
#	3 = VERBOSE (all messages)
#
EithonDebugLevel: 3

#
# The number of minutes that a player may be inactive before we stop the play time timer.
InactivityMinutes: 5

messages:

	#
	# Parameters: <player name> (%s)
	PlayerStarted: Started recording play time for player %s.

	#
	# Parameters: <player name> (%s)
	PlayerStopped: Stopped recording play time for player %s.

	#
	# Parameters: -
	PlayerAwayFromKeyboard: AFK with description \"%s\".

	#
	# Parameters: -
	Saved: Saved play times for all logged in players.

	#
	# AFK message when detected by the plugin
	# Parameters: -
	InactivityDetected: Inactivity detected

	#
	# AFK default description (when issuing the command /stats afk, but without a description).
	# Parameters: -
	DefaultAfkDescription: BRB
	