#
# The number of seconds that a player may be inactive before we stop the play time timer.
AllowedInactivityInSeconds: 300

#
# The number of seconds between saving the current statistics.
# This is the time that you risk to lose statistics for if your server crashes.
SecondsBetweenSave: 300

#
# The time of day to archive the day statistics. Recommended: 00:00
ArchiveAtTimeOfDay: 00:00

eithon:
  UseMarkUpForMessages: 0
  UseWrappingForMessages: 0
  
  #
  # Debug level
  #  0 = NONE (no debug messages)
  #  1 = MAJOR (only major messages)
  #  2 = MINOR (also minor messages)
  #  3 = VERBOSE (all messages)
  #
  EithonDebugLevel: 1

messages:

  #
  # Parameters: -
  PlayerIdle: Idle

  #
  # Parameters: <player name> (%s)
  PlayerStarted: Started recording play time for player %s.

  #
  # Parameters: <player name> (%s)
  PlayerStopped: Stopped recording play time for player %s.

  #
  # Parameters: <play time> (%s) <player name> (%s) <total play time> (%s) 
  PlayTimeAdded: Added %s play time to player %s, resulting in a total play time of %s.

  #
  # Parameters: -
  Saved: Saved play times for all logged in players.

  #
  # AFK message when detected by the plugin
  # Parameters: -
  InactivityDetected: Inactivity detected

  #
  # AFK default description (when issuing the command /stats afk, but without a description).
  # Parameters: -
  DefaultAfkDescription: BRB
  
  #
  #
  # Parameters: <Player> (%s), <Description> (%s)
  ToAfkBroadcast: Player %s is AFK (%s)
  
  #
  #
  # Parameters: <Player> (%s)
  FromAfkBroadcast: Player %s is back
  
  #
  #
  # Parameters: <Description> (%s)
  AfkYes: "Yes (%s)"
  
  #
  #
  # Parameters: -
  AfkNo: "No"
  
  #
  # The following messages have the following possible parameters
  # %PLAYER_NAME%: The name of the player that the statistics is for.
  # %AFK_DESCRIPTION%: The AFK reason. Empty if not AFK.
  # %BLOCKS_BROKEN%: The total number of blocks that the player has broken.
  # %BLOCKS_CREATED%: The total number of blocks that the player has created.
  # %BLOCKS_CREATED_OR_BROKEN%: The total number of blocks that the player has created or broken (the sum).
  # %CHAT_ACTIVITIES%: The number of chats that the player has sent
  # %INTERVALS%: The number of time intervals that has been recorded for the player.  
  # %TOTAL_PLAY_TIME%: The total play time for the player.
  # %LONGEST_INTERVAL%: The longest time that the player has played without a break.
  # %LATEST_INTERVAL%: The latest recorded play time for the player.
  TimeStats: "%TOTAL_PLAY_TIME% in %INTERVALS% intervals (longest %LONGEST_INTERVAL%, latest %LATEST_INTERVAL%) AFK: %AFK_DESCRIPTION%"
  ChatStats: "%CHAT_ACTIVITIES% chats"
  BlockStats: "%BLOCKS_CREATED% blocks created (broken %BLOCKS_BROKEN%)"
  PlayerStats: "	[hl=1][ [color=aqua]%PLAYER_NAME% Stats [/color] ]\n[color=darkgrey]  -[/color] [color=darkaqua]Playtime:[/color] %TOTAL_PLAY_TIME% \n[color=darkgrey]  -[/color] [color=darkaqua]Messages Sent:[/color] %CHAT_ACTIVITIES% \n[color=darkgrey]  -[/color] [color=darkaqua]Blocks Placed/Broken:[/color] %BLOCKS_CREATED%/%BLOCKS_BROKEN% \n[color=darkgrey]  -[/color] [color=darkaqua]AFK:[/color] %AFK_DESCRIPTION% "
  DiffStats: "%TOTAL_PLAY_TIME% in %INTERVALS% intervals, %CHAT_ACTIVITIES% chats, %BLOCKS_CREATED_OR_BROKEN% blocks created or broken)%TOTAL_PLAY_TIME% in %INTERVALS% intervals, %CHAT_ACTIVITIES% chats, %BLOCKS_CREATED_OR_BROKEN% blocks created or broken)"
