name: EithonStats
main: net.eithon.plugin.stats.Plugin
version: 1.0
author: vanbrayne
description: Player statistics
depend: [EithonLibrary]
commands:
  estats:
    description: Control jump pads
    usage: /estats status | player | start | stop | diff | afk | save | time | blocks | chat | add
    permission-message: You don't have <permission>
permissions:
  estats.*:
    description: Gives access to all estats commands
    default: op
    estats.player: true
    estats.start: true
    estats.stop: true
    estats.afk: true
    estats.save: true
    estats.time: true
    estats.blocks: true
    estats.chat: true
    estats.diff: true
    estats.add: true
  estats.status:
    description: Access to /estats status command
    default: op
  estats.player:
    description: Access to /estats player command
    default: op
  estats.start:
    description: Access to /estats start command
    default: op
  estats.stop:
    description: Access to /estats stop command
    default: op
  estats.afk:
    description: Access to /estats afk command
    default: op
  estats.save:
    description: Access to /estats save command
    default: op
  estats.time:
    description: Access to /estats time command
    default: op
  estats.blocks:
    description: Access to /estats blocks command
    default: op
  estats.chat:
    description: Access to /estats chat command
    default: op
  estats.diff:
    description: Access to /estats diff command
    default: op
  estats.add:
    description: Access to /estats add command
    default: op
