name: EithonStats
main: net.eithon.plugin.stats.Plugin
version: 1.0
author: vanbrayne
description: Player statistics
depend: [EithonLibrary]
commands:
  estats:
    description: Control jump pads
    usage: /estats status | player | start | stop | diff | afk | save | time | blocks | chat | add
    permission-message: You don't have <permission>
permissions:
  stats.*:
    description: Gives access to all estats commands
    default: op
    stats.player: true
    stats.start: true
    stats.stop: true
    stats.afk: true
    stats.save: true
    stats.time: true
    stats.blocks: true
    stats.chat: true
    stats.diff: true
    stats.add: true
  stats.status:
    description: Access to /estats status command
    default: op
  stats.player:
    description: Access to /estats player command
    default: op
  stats.start:
    description: Access to /estats start command
    default: op
  stats.stop:
    description: Access to /estats stop command
    default: op
  stats.afk:
    description: Access to /estats afk command
    default: op
  stats.save:
    description: Access to /estats save command
    default: op
  stats.time:
    description: Access to /estats time command
    default: op
  stats.blocks:
    description: Access to /estats blocks command
    default: op
  stats.chat:
    description: Access to /estats chat command
    default: op
  stats.diff:
    description: Access to /estats diff command
    default: op
  stats.add:
    description: Access to /estats add command
    default: op
