name: EithonStats
main: net.eithon.plugin.stats.EithonStatsPlugin
version: ${project.version}
author: vanbrayne
description: Player statistics
softdepend: [EithonCop]
depend: [EithonLibrary]
commands:
  estats:
    description: Control jump pads
    usage: /estats add | afk | blocks | chat | diff | for | remove | reset | save | status | start | stop | time | who
    permission-message: You don't have <permission>
permissions:
  estats.*:
    description: Gives access to all estats commands
    default: op
    stats.for: true
    stats.start: true
    stats.stop: true
    stats.afk: true
    stats.save: true
    stats.time: true
    stats.blocks: true
    stats.chat: true
    stats.diff: true
    stats.add: true
    stats.remove: true
    stats.reset: true
    stats.who: true
  estats.status:
    description: Access to /estats status command
    default: op
  estats.for:
    description: Access to /estats for command
    default: op
  estats.start:
    description: Access to /estats start command
    default: op
  estats.stop:
    description: Access to /estats stop command
    default: op
  stats.afk:
    description: Access to /estats afk command
    default: op
  estats.save:
    description: Access to /estats save command
    default: op
  estats.time:
    description: Access to /estats time command
    default: op
  estats.blocks:
    description: Access to /estats blocks command
    default: op
  estats.chat:
    description: Access to /estats chat command
    default: op
  estats.diff:
    description: Access to /estats diff command
    default: op
  estats.add:
    description: Access to /estats add command
    default: op
  estats.remove:
    description: Access to /estats remove command
    default: op
  estats.reset:
    description: Access to /estats reset command
    default: op
  estats.who:
    description: Access to /estats who command
    default: op
