name: EithonStats
main: net.eithon.plugin.stats.Plugin
version: 0.1
author: vanbrayne
description: Player statistics
depend: [EithonLibrary]
commands:
  stats:
    description: Control jump pads
    usage: /stats player | start | stop | afk | save | time
    permission-message: You don't have <permission>
permissions:
  stats.*:
    description: Gives access to all stats commands
    default: op
    stats.player: true
    stats.start: true
    stats.stop: true
    stats.afk: true
    stats.save: true
    stats.time: true
  stats.player:
    description: Access to /stats player command
    default: op
  stats.start:
    description: Access to /stats start command
    default: op
  stats.stop:
    description: Access to /stats stop command
    default: op
  stats.afk:
    description: Access to /stats afk command
    default: op
  stats.save:
    description: Access to /stats save command
    default: op
  stats.time:
    description: Access to /stats all command
    default: op
